# Welcome to GitHub Pages!  This file has been simplified to the bare essentials.

title: Replace this with your title # this is the part at the top
email: Replace this with your email # this is your email address
description: >- # this means to ignore newlines until "baseurl:" (ignore this)
  Replace this with a description, which will be shown at the bottom
baseurl: "/" # the subpath of your site, e.g. /blog (don't touch this)
url: "Replace this with https://yourname.github.io" # do as it says
#twitter_username: jekyllrb
github_username:  Replace this with your github username

# Build settings (ignore this unless you're changing the theme)
theme: minima
plugins:
  - jekyll-feed